/*Why should I copyright?*/

package com.dont_leave.hrdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


public interface HrdbQueryExecutorService {


}


